# Generated by Django 4.2.5 on 2023-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('specialist', models.CharField(max_length=200)),
                ('practiceType', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
